### ISSUE TITLE
Is this ppa will be updated?

### ISSUE THREAD

**Issue by KabbAmine** [zealdocs/zeal-ubuntu#1]
Hi.

Are you planning to add the [new zeal version(s)](https://github.com/zealdocs/zeal/releases/tag/v0.1.0) in this ppa?

**Comment by jkozera** [comment]
Hi. There's a new PPA at https://launchpad.net/~zeal-developers/+archive/ubuntu/ppa. Hopefully later today I will update my personal one to link to the new one. (by showing a message on Zeal launch, which is already prepared but not yet published - see https://github.com/zealdocs/zeal-ubuntu-transitional)

**Comment by KabbAmine** [comment]
Great news :smile: (I suppose that the site will follow soon).

Thanks for your work.
