### ISSUE TITLE
cann't run ZEAL

### ISSUE THREAD

**Issue by collinswang** [zealdocs/zeal-ubuntu#2]
UBUNTU 14.04
alerady install QT5.0 and ubuntu SDK 
and already install "sudo apt-get install "^libxcb.*" libx11-xcb-dev libglu1-mesa-dev libxrender-dev"
but running ZEAL ,  show me follow error : 
"This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
"
could you help me ?

**Comment by trollixx** [comment]
Something weird with your dependencies. Ubuntu 14.04 should have Qt 5.2.1, not 5.0. A full system upgrade, perhaps, could solve the issue.

**Comment by trollixx** [comment]
Closing due to no response for a long time.

**Comment by chaoqing** [comment]
It is so wired! After installed the ppa version, I came cross the same problem as @collinswang did. So I compile the sourch code myself. And then I found that the binary file `/usr/bin/zeal` would work when it was moved to `/usr/local/bin/` or any other dirctory. It just report `can not load xcb` when zeal( ppa version or self compiled version) is in `/usr/bin/`. No idea why this happened.

**Comment by trollixx** [comment]
@chaoqing Do you have several Qt versions installed in your system?

**Comment by chaoqing** [comment]
Yes, I have both qt4.8.6 and qt5.2.1 installed. And I am using the ubuntu server 14.04.2 + openbox.
